# Generated by Django 6.0.3 on 2026-04-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_booking_owner_cancel_alter_login_table_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='rent_perday',
            new_name='base_rent_perday',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='weekend_multiplier',
            field=models.FloatField(default=1.5, help_text='Weekend rate multiplier'),
        ),
    ]
