# Generated by Django 6.0.3 on 2026-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_rent_perday_vehicle_base_rent_perday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_table',
            name='reset_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='login_table',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
